/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "OSMCAL_interface.h"
#include "main.h"
#include "RCC_interface.h"
#include "GPIO_interface.h"

#define CHANNEL1_PORT          PORTC
#define CHANNEL1_PIN           PIN8

#define CHANNEL2_PORT          PORTC
#define CHANNEL2_PIN           PIN6

#define CHANNEL3_PORT          PORTC
#define CHANNEL3_PIN           PIN5

#define CHANNEL4_PORT          PORTC
#define CHANNEL4_PIN           PIN9

#define DELAY_1MS           1250U
#define DELAY_1S            (1000u * (DELAY_1MS))
#define DELAY_500MS         (500u * (DELAY_1MS))
#define DELAY_250MS         (250u * (DELAY_1MS))
#define DELAY_125MS         (125u * (DELAY_1MS))

void Delay(uint32_t Count)
{
	uint32_t i ;
	for(i=0 ; i<Count;i++);
}

int main(void)
{
	PinConfig_t Channel1 =
	{
			.Port = CHANNEL1_PORT,
			.PinNum = CHANNEL1_PIN,
			.Mode = OUTPUT,
			.OutputType = PUSH_PULL,
			.Speed = LOW ,
			.PullType = NOPULL
	};

	PinConfig_t Channel2 =
		{
				.Port = CHANNEL2_PORT,
				.PinNum = CHANNEL2_PIN,
				.Mode = OUTPUT,
				.OutputType = PUSH_PULL,
				.Speed = LOW ,
				.PullType = NOPULL
		};

	PinConfig_t Channel3 =
		{
				.Port = CHANNEL3_PORT,
				.PinNum = CHANNEL3_PIN,
				.Mode = OUTPUT,
				.OutputType = PUSH_PULL,
				.Speed = LOW ,
				.PullType = NOPULL
		};

	PinConfig_t Channel4 =
		{
				.Port = CHANNEL4_PORT,
				.PinNum = CHANNEL4_PIN,
				.Mode = OUTPUT,
				.OutputType = PUSH_PULL,
				.Speed = LOW ,
				.PullType = NOPULL
		};
	RCC_AHB1EnableClk(AHB1_GPIOC);

	GPIO_u8PinInit(&Channel1);
	GPIO_u8PinInit(&Channel2);
	GPIO_u8PinInit(&Channel3);
	GPIO_u8PinInit(&Channel4);

	EnableSystemFaults();
	STK_voidInit(1000);
	Stack_voidSchedulerStackInit(SCHED_TASK_STACK);
	InitTaskStack();
	ChangeToPSP();
	Task1_Handler();
    /* Loop forever */
	for(;;);
}

void Task1_Handler(void)
{
	while(1)
	{
		GPIO_u8TogglePinValue(CHANNEL1_PORT, CHANNEL1_PIN);
		TaskDelay(1000);
	}
}
void Task2_Handler(void)
{
	while(1)
	{
		GPIO_u8TogglePinValue(CHANNEL2_PORT, CHANNEL2_PIN);
		TaskDelay(500);
	}
}
void Task3_Handler(void)
{
	while(1)
	{
		GPIO_u8TogglePinValue(CHANNEL3_PORT, CHANNEL3_PIN);
		TaskDelay(250);
	}
}
void Task4_Handler(void)
{
	while(1)
	{
		GPIO_u8TogglePinValue(CHANNEL4_PORT, CHANNEL4_PIN);
		TaskDelay(125);
	}
}
